#+TITLE: CE 615: Structural Design for Fire - Spring 2025
# #+OPTIONS: 
#+OPTIONS: toc:1



* Basic Information
|-------------------+-----------------------------------------|
| Class timings     | Wednesday, Friday, 15:30-16:50 hrs     |
| Class location    | AB 7/210                                |
|-------------------+-----------------------------------------|
| Instructor        | Gaurav Srivastava (gauravs@iitgn.ac.in) |
|-------------------+-----------------------------------------|


Remaining information will be updated soon.

* Course objectives, syllabus, books, pre-requisites
** Objectives
- To learn about the effects of fire on reinforced concrete and steel structures.
- To learn about the behavior and characterization of fires of different kinds.
- To be able to design reinforced concrete and steel structures under fire conditions.
	
** Syllabus
- Fire characteristics (combustion, ignition, flammability limits, etc.)
- Properties of steel and concrete at high temperatures.
- Heat transfer mechanisms: conduction, convection and radiation. Mathematical modeling of the heat transfer problem.
- Fire as a hazard; development of a fire in the open and in a compartment.
- Stages of a compartment fire: pre-flashover, flashover and post-flashover.
- Characterization of a fire through time-temperature and time-HRR; t^2 fire model.
- Estimation of fire curves through fire load energy density and compartment characteristics. Ventilation factor; fuel vs. ventilation controlled fire.
- Design and parametric fire curves.
- Heat transfer within concrete structures (semi-infinite idealization) and steel structures (lumped capacity idealization).
- Empirical and code-based methods to compute temperature within structural systems.
- Design of steel structures under fire.
- Design of reinforced concrete structures under fire; 500 isotherm method, zone method.
- Equivalent fire severity.
		
** Textbook
- Fire-resistant Design of Structures by S. Chandrasekaran and G. Srivastava, CRC Press.
# comment
	
** Reference Books
- Fundamentals of Heat and Mass Transfer by T.L. Bergman, A.S. Lavine, F.P. Incropera and D.P. Dewitt, John Wiley & Sons.
- An Introduction to Fire Dynamics by D. Drysdale, Wiley.
- Temperature calculation in Fire Safety Engineering by U. Wickstrom, Springer.
  
** Codes and Standards
- National Building Code (NBC) 2016 of India.
- IS 800 (steel) and IS 456 (reinforced concrete)
- Eurocode EN 1990:2002 (basis of structural design)
- Eurocode EN 1991-1-1 and EN 1991-1-2 (actions)
- Eurocode EN 1992-1-1 and EN 1992-1-2 (reinforced concrete)
- Eurocode EN 1993-1-1 and EN 1993-1-2 (steel)
- Eurocode EN 1996-1-1 and EN 1996-1-2 (masonry)

* Course Policies
** Etiquette
- Please be considerate about everyone's time.
- In all emails pertaining to this course, please have "CE615" in the subject line.
	- (note that there is no space or hyphen or anything between CE and 615)

** Cheating
Cheating cases (assignments/codes/exams/project) will be dealt with in accordance with the Institute norms. It is expected that everyone will uphold the honor code.

** Grading
Following will be the weightage of different components of assessment
| Component            | Weightage |
|----------------------+-----------|
| Homework assignments |       30% |
| Group projects       |       30% |
| Exams (two)          |  20% each |

** Modes of formal assessment
- Assignments will entail analysis/practical problems, coding, reports, etc. and may be individual or group.
- Group projects will involve more aggregating tasks including coding, use of a software, or design of larger systems.
	
** Emphasis on self-learning
It is important to develop the habit of self-learning. A number of reading assignments and self-exercises will be given during the course. These will not be formally graded and it will be expected that students will go through them on a regular basis on their own.

* Calendar (tentative)
** [L1] Jan 03, Fri
- Introduction to fire engineering and design.
** [L2] Jan 08, Wed
- Combustion, ignition, autoignition, fire triangle and tetrahedron.
- Flash point and fire point. Flammability limits, limiting oxygen concentration.
- General chemical reaction of combustion.
- Refer to the textbook (Chapter 1).
** [L3] Jan 10, Fri
- Thermal and mechanical properties of steel at elevated temperatures - codes and standards vs. literature.
- Structural steel vs. reinforcing steel.
- Refer to the textbook (Chapter 1).
** [L4] Jan 15, Wed
- Thermal and mechanical properties of concrete at elevated temperatures - codes and standards vs. literature.
- Normal strength vs. high strength concrete.
- Refer to the textbook (Chapter 2).
** [L5] Jan 17, Fri
- Concepts of temperature, heat and heat flux.
- Modes of heat transfer. Fourier's law, Newton's law of cooling, and Stefan's law of radiation.
- Derivation of the transient heat equation along with three kinds of boundary conditions.
- Refer to Wickstrom's book (Chapter 1). Questions to reflect on:
  1. How are heat and temperature of a body related?
  2. What is heat flux? What is the heat flux in case of conduction?
  3.  What is Fourier's law of heat conduction?
  4. What is first kind of boundary condition? What is another name for it?
  5. What is second kind of boundary condition? What is another name for it?
  6. What is third kind of boundary condition? What is another name for it?
  7. What is an adiabitic surface?
  8. How is third kind of boundary condition related to Newton's law of cooling?
  9. How can one calculate heat flux gain due to radiation?
  10. What is the difference between incident, absorbed, and emitted heat flux?
  11. What is absorptivity coefficient, what is emissivity?
  12. What is Stefan-Boltzmann law?
  13. What is Kirchhoff's identity?
  14. What is the mixed boundary condition that incorporates both convection and radiation?
  15. Derive the transient heat conduction equation in one dimension. How is the time change rate related to spatial heat flow?
  16. What is thermal diffusivity?
  17. Explain the electric circuit analogy for thermal problems in one dimension.
** [L6] Jan 22, Wed
- Electrical circuit analogy for heat transfer.
- Steady-state heat conduction.
- Refer to Wickstrom's book (Chapter 2). Questions to reflect on:
  1. Write Fourier's law of conduction using the electrical circuit analogy and define thermal resistance due to conduction.
  2. How is 1D heat transfer equation useful in modeling heat transfer through a wall?
  3. What will be the thermal resistance of a wall comprising of multiple layers?
  4. Define the thermal resistance due to convection (surface thermal resistance).
  5. Derive steady-state heat conduction relation from the transient equation. 
** [L7] Jan 24, Fri
- Lumped-capacity model and unsteady heat equation for this idealization.
- Consideration with different boundary conditions. Relevance of boundary conditions w.r.t. different fire exposure conditions.
- Refer to Wickstrom's book (Chapter 3). Questions to reflect on:
  1. What is meant by lumped heat capacity?
  2. Write the dynamic energy balance equation for a material modeled using lumped heat capacity assumption. What is the dimensionality of this problem?
  3. What is the thermal resistance in case of unprotected vs. protected steel structures, when modeled using this approach?
  4. What is the electrical circuit analogy in this case? What is heat capacitance per unit area?
  5. What is time constant?
  6. Derive an expression for calculating steel temperature, when exposed to a varying gas temperature.
  7. What is Biot number? How does it provide guidance on the applicability of the lumped heat capacity assumption?
** [L8] Jan 29, Wed
- Boundary conditions in fire protection engineering.
- Combined convective and radiative boundary conditions. Adiabitic surface temperature.
- Refer to Wickstrom's book (Chapter 4). Questions to reflect on:
  1. How are the different fluxes (incident, absorbed, reflected, emitted, [transmitted]) related through energy balance?
  2. How can the convective and radiative boundary conditions be combined through a common heat transfer coefficient?
  3. What is the form of this combined heat transfer coefficient?
  4. What is the difference between gas temperature and fire temperature? How do these affect convection and radiation?
  5. Under what conditions, can these two temperatures be considered the same?
  6. What is AST (adiabitic surface temperature) and how is it related to the above two temperatures?
  7. What is the electrical circuit analogy for AST?
  8. What is the importance of plate thermocouples? Which temperature do they measure? Is there any effect of direction on plate thermocouple?
  9. How can the time constant of plate thermocouple be calculated?
** [L9] Jan 31, Fri
- Radiative heat transfer.
- Stefan's law, model parameters. View factors.
- Radiation from flames and smoke. Provisions from codes.
- Refer to Wickstrom's book (Chapter 5). Questions to reflect on:
  - What is a blackbody?
  - What is Stefan-Boltzmann law? How can it be derived?
  - What is Kirchhoff's identity? How can it be arrived at? What are the assumptions?
  - What is view factor? How does it affect radiation?
  - Derive the reciprocity relation pertaining to view factors.
  - Derive the relation of radiation between two infinite parallel planes.
  - How can radiation shields be used to reduce the impact of radiation from fires?
  - What are view factors between different elements and planes oriented in different directions?
  - How does the distance between two surfaces affect radiative heat transfer?
  - How can the emissivity and absorptivity of flames and smoke be estimated? What are the typical values for fuels arising from common fuels?
** [L10] Feb 05, Wed
- *Assignment 1 given* (due on 12.02.25) [[https://drive.google.com/drive/folders/1JwitDJ-MCzK7mHEF9tC9tDC6imD3d-Pw?usp=sharing][download from here]]
- *Group Project 1 given* (due on 28.02.25) [[https://drive.google.com/drive/folders/1JwitDJ-MCzK7mHEF9tC9tDC6imD3d-Pw?usp=sharing][download from here]]
- Convective heat transfer.
- Free/natural and force convection. Convective heat transfer coefficients. Provisions from codes.
- Refer to Wickstrom's book (Chapter 6). Questions to reflect on:
  - What is natural or free convection?
  - What are the heat transfer properties of air and water? How do they affect convection?
  - What is Prandtl's number?
  - What is forced convection?
  - What is Nusselt number? How is it useful to estimate forced convection heat transfer?
  - Plot the relation between convective heat transfer in air as a function of temperature and velocity.
  - Study and explain Figure 6.5 of the book.
  - h = 25 W/m^2K is a commonly used convective heat transfer coefficient for air. Under what conditions is this value useful?
** [L11] Feb 07, Fri
- Consideration of 2D transient heat transfer equation and its numerical solution via finite difference method.
- Refer to textbook (Section 3.22). Questions to reflect on:
  - Derive the 2D transient heat transfer equation.
  - How can this be discretized in space and time using finite difference method?
  - How will the three different kinds of boundary conditions be applied numerically?
  - What are the requirements for numerical stability of the solution?
** [L12] Feb 12, Wed
- *Assignment 2 given* (due on 19.02.25) [[https://drive.google.com/drive/folders/1JwitDJ-MCzK7mHEF9tC9tDC6imD3d-Pw?usp=sharing][download from here]]
- Consideration of 2D transient heat transfer equation and its numerical solution via finite difference method.
- Refer to textbook (Section 3.22). Questions to reflect on:
  - Derive the 2D transient heat transfer equation.
  - How can this be discretized in space and time using finite difference method?
  - How will the three different kinds of boundary conditions be applied numerically?
  - What are the requirements for numerical stability of the solution?
** [L13] Feb 14, Fri
- Temperature calculations for steel structures. Lumped-capacity and detailed calculation approaches.
- Refer to textbook (Section 3.24) and Wickstrom's book (Chapter 13). Questions to reflect on:
** [L14] Feb 19, Wed
- *Assignment 3 given* (due on 28.02.25) [[https://drive.google.com/drive/folders/1JwitDJ-MCzK7mHEF9tC9tDC6imD3d-Pw?usp=sharing][download from here]]
- Temperature calculations for steel structures. Lumped-capacity and detailed calculation approaches.
- Refer to textbook (Section 3.24) and Wickstrom's book (Chapter 13). Questions to reflect on:
** [L15] Feb 21, Fri
- Temperature calculations for concrete structures. Semi-infinite idealization and detailed calculation approaches.
- Refer to textbook (Section 3.25) and Wickstrom's book (Chapter 14). Questions to reflect on:
** Feb 26, Wed - no class
- Maha Shivaratri
** [L16] Feb 28, Fri
- Temperature calculations for concrete structures. Semi-infinite idealization and detailed calculation approaches.
- Refer to textbook (Section 3.25) and Wickstrom's book (Chapter 14). Questions to reflect on:
** Mar 1 - 7: Mid semester exam week
** Mar 8 - 16: Mid semester recess
** [L17] Mar 19, Wed
- Stages of a compartment fire. Pre-flashover, flashover and post-flashover.
- Zone models for pre-flashover and post-flashover stage. Empirical models to predict flashover.
- Refer to textbook (Section 3.9) and Wickstrom's book (Chapter 10, 11). Questions to reflect on:
** [L18] Mar 21, Fri
- HRR-time models for fire (t^2 model) and their relation with the nature of combustibles.
- Estimation of fire load energy density.
- Parametric time-temperature fire curves.
- Refer to textbook (Section 3.16) and Wickstrom's book (Chapter 12). Questions to reflect on:
** [L19] Mar 26, Wed
- Standard fire models. Equivalent fire severity.
- Refer to textbook (Section 3.19, 3.20) and Wickstrom's book (Chapter 12). Questions to reflect on:
** [L20] Mar 28, Fri
- Limit states for design under fire.
- Design calculations for steel structures (tension members).
- Refer to textbook (Section 3.27, 3.28). Questions to reflect on:
** [L21] Apr 02, Wed
- Design calculations for flexural members (steel and concrete).
- Refer to textbook (Section 3.29). Questions to reflect on:
** [L22] Apr 04, Fri
- Design calculations for flexural members (steel and concrete).
- Refer to textbook (Section 3.29). Questions to reflect on:
** [L23] Apr 09, Wed
- Design calculations for compression members (steel and concrete).
- Refer to textbook (Section 3.30). Questions to reflect on:
** [L24] Apr 11, Fri
- Design calculations for compression members (steel and concrete).
- Refer to textbook (Section 3.30). Questions to reflect on:
** [L25] Apr 16, Wed
- Design of fire protection for steel structures.
- Refer to textbook (Section 3.26.1) and Wickstrom's book (Chapter 13). Questions to reflect on:
** Apr 18, Fri - no class
- Good Friday
** [L26] Apr 23, Wed
- Summary and recap.
** Apr 24 - 30: End semester exam week
