#+TITLE: CE 312: Design of Steel Structures - Fall 2026
# #+OPTIONS: 
#+OPTIONS: toc:1
#+MACRO: mtime (eval (format-time-string "%d-%B-%Y" (nth 5 (file-attributes buffer-file-name))))

* Basic Information
|-------------------+------------------------------------------------------------------------------------|
| Class timings     | Tuesday and Thursday, 10:00 - 11:20                                                |
| Class location    | AB 7/101                                                                           |
|-------------------+------------------------------------------------------------------------------------|
| Tutorial timings  | Friday, 8:30 - 9:50                                                                |
| Tutorial location | AB 7/210                                                                           |
|-------------------+------------------------------------------------------------------------------------|
| Instructor        | Gaurav Srivastava (gauravs@iitgn.ac.in)                                            |
|-------------------+------------------------------------------------------------------------------------|
| TAs               | Yajat Sharma (yajat.sharma@iitgn.ac.in) and Kritika Rai (kritika.rai@iitgn.ac.in). |
|-------------------+------------------------------------------------------------------------------------|

- Assignments and tutorials will be posted in this [[https://drive.google.com/drive/folders/1ybyPiNYI5DZvWuvHqebnKAR2_mrrkjlk?usp=sharing][Google folder]]

* Course objectives, syllabus, books, pre-requisites
** Objective
- To learn the basics of analysis and design of steel structures.
	
** Syllabus
- Review of Design Philosophy: Working stress (WS), Ultimate load (UL), Load resistant factor design (LRFD), and Limit state (LS); characteristics load vs. strength; Load combinations; and Partial safety factors
- Elementary Plastic Analysis: Moment-curvature relationship; Plastic hinges; and Collapse load and Mechanism
- Design of Pure Tension and Pure Compression Members: Bolted vs welded members; Theory of elastic buckling with and without imperfection; Long and short column effects; and P-Delta effect
- Design of Beams and Plate Girders: Kirchhoff's plate bending theory; Plate buckling; Torsional and Lateral-torsional buckling; Design of laterally supported and unsupported beams; and Rolled steel vs built-up sections
- Design of Beam-Columns: Combined effect of axial and flexure (P-M interaction), Design of columns subjected to axial force and uniaxial / biaxial moment; and Rolled steel vs built-up sections
- Design of Beam-Column Joints: Strong vs weaker axis connections; Moment-shear connection, Torsion-shear connection; and Bolted vs welded connections
- Design of Column-Base Plate Connections: Bolted vs welded connections; Axial force and uniaxial / biaxial moment; and Uplift and Anchor bolts. 

** Text Books
- Design of Steel Structures by N. Subramanian. (primary)
- Structural Steel Design by McCormac and Csernak. (secondary)

** Relevant Codes
- IS 800:2007 (main design code)
- IS 875 (specification of design loads)
- IS 808:1989, 1732:1989, 1173:1978 (dimensions of hot rolled sections)
- IS 2062:2011 (specifications of hot rolled structural steel)
Codes can be downloaded free of charge from the BIS website: https://standardsbis.bsbedge.com/.
- Please ensure that you have a copy of all of these codes BEFORE the first class.
- During the exams, only clean hard copies of the codes will be allowed.

** Analysis and Design Software
SAP2000 will be utilized for analysis and design during the course. Following are some useful videos on youtube to learn analysis in SAP2000:
- Modeling and analysis of trusses
  - https://www.youtube.com/watch?v=pOEV-sm2Owk
  - https://www.youtube.com/watch?v=sTeiPkhfNPU
  - https://www.youtube.com/watch?v=eGhfhR7zVgM
- Building design playlist: https://www.youtube.com/playlist?list=PLHTVTvUaTtbDwDkxji2CkU_nhI3zEKMLB

* Course Policies
** Etiquette
- Please be considerate about everyone's time.
- In all emails pertaining to this course, please have "CE312" in the subject line.
	- (note that there is no space or hyphen or anything between CE and 312)

** Cheating and Plagiarism
Cheating cases (assignments/codes/exams/project) will be dealt with in accordance with the Institute norms. It is expected that everyone will uphold the honor code.

** Late submissions
Late submissions will not be considered towards grades.

** Attendance
- It is expected that students will attend all the lectures and tutorials. Leave will be granted only in genuine cases with appropriate documentation, when sought ahead of time.
- Attendance will be recorded in all the sessions and the present percentage will be multiplied to the total marks before calculation of the final marks for grading.
- For example, if the total marks are 90/100 and the attendance is 85%, the final marks considered for grading will be $90\times 85\% = 76.5/100$.

** Grading
Following will be the weightage of different components of assessment
| Component            | Weightage |
|----------------------+-----------|
| Homework assignments |       20% |
| Exam 1               |       20% |
| Exam 2               |       20% |
| Project 1            |       25% |
| Project 2            |       15% |

- Assignments and tutorials will be posted in this [[https://drive.google.com/drive/folders/1FFy2mhmzlJjk1cDJ6ZzLTR_JR9H3c3Tv?usp=sharing][Google folder]].
	
** Emphasis on self-learning
It is important to develop the habit of self-learning. A number of reading assignments and self-exercises will be given during the course. These will not be formally graded and it will be expected that students will go through them on a regular basis on their own.

* Projects
There will be two projects in this course that are to be done in groups.

** Project 1 - design and build a portable cabin
- The project entails designing and building a portable cabin as per the schematic and requirements mentioned [[https://drive.google.com/file/d/1JQVniTTRtjY1xVj0pmJTRHAVW6blZKlP/view?usp=drive_link][here]].
- The project will be carried out in groups of 9-10 students.
- A break-up of the tasks for Project 1 are as follows:
  - Task 1: survey to obtain user requirements
  - Task 2: geometrical/space design
  - Task 3: load estimation and preliminary structural analysis
  - Task 4: design of structural members
  - Task 5: design of connections
  - Task 6: preparation of fabrication drawings
  - Task 7: preparation of BOQ and cost estimate
  - Task 8: fabrication of the cabin
  - Task 9: putting the cabin to use and collecting feedback
  - Task 10: submission of final report

** Project 2 - design of industrial shed
- The project entails designing of an industrial shed of plan dimensions 10m width and 50m length and a height of 6m.
- The project will be carried out in groups of 5-6 students.
- A break-up of the tasks for Project 2 are as follows:
  - Task 1: load estimation and preliminary structural analysis
  - Task 2: design of structural members
  - Task 3: design of connections
  - Task 4: design of foundation
  - Task 5: revision of structural analysis model
  - Task 6: preparation of structural drawings
  - Task 7: submission of final report


* Calendar (tentative)

#+BEGIN_EXPORT HTML
<style>
table {border-collapse: collapse; width: 100%;}
th, td {border: 1px solid black; padding: 8px; text-align: left;}
th {background-color: #f2f2f2;}
</style>
<table>
<tr><th>Date</th><th>Lec/Tut</th><th>Activities</th></tr>
<tr><td>Aug 04, Tue</td><td>L1</td><td>
Topics
<ul>
<li>Introduction to steel structures. </li>
<li>Introduction to design. </li>
<li>Probabilistic nature of load and resistance.</li>
</ul>

</td></tr>
<tr><td>Aug 06, Thu</td><td>L2</td><td>
Topics
<ul>
<li>Characteristic load and resistance. </li>
<li>Limit state function. </li>
<li>Normal distribution (pdf, cdf). </li>
<li>Different measures of reliability indices and their relation with probability of failure. </li>
<li>Process of manufacturing steel from iron ore (<a href="https://www.youtube.com/watch?v=OjWWcsocnJk" target=\"_blank\">video on steel manufacturing</a>).</li>
</ul>

</td></tr>
<tr><td>Aug 07, Fri</td><td>L3</td><td>
Topics
<ul>
<li>Characteristic vs. Design load and resistance. </li>
<li>LRFD format. Partial safety factors. </li>
<li>Limit state method of design. </li>
<li>Partial factors for load and resistance as per IS 800. </li>
<li>Grades of steel as per IS 800 and IS 2062. </li>
<li>UTS of steel specimens. Mechanical properties of steel (<a href="https://www.youtube.com/watch?v=D8U4G5kcpcM" target=\"_blank\">video on UTS</a>).</li>
<li>Chemical composition and weldability.</li>
</ul>

</td></tr>
<tr><td>Aug 11, Tue</td><td>L4</td><td>
Topics
<ul>
<li>Structural steel products in India. </li>
<li>Hot rolling process (<a href="https://www.youtube.com/watch?v=6xnKmt_gsLs" target=\"_blank\">video on hot rolling process</a>).</li>
<li>Major and minor axes. Section classes properties from IS 808. </li>
<li>General process of design leading to the selection of appropriate section class. </li>
<li>Load specifications in IS 875.</li>
</ul>

</td></tr>
<tr><td>Aug 13, Thu</td><td>L5</td><td>
Topics
<ul>
<li>Loads and load combinations. </li>
<li>Limit state of gross-section yielding and net-section rupture for tension members. </li>
<li>Stress concentration factor.</li>
</ul>

</td></tr>
<tr><td>Aug 14, Fri</td><td>T1</td><td>

Tutorial:
<a href="https://drive.google.com/drive/folders/1ybyPiNYI5DZvWuvHqebnKAR2_mrrkjlk" target=\"_blank\">T-1</a> <br>
Assignment:
<a href="https://drive.google.com/drive/folders/1ybyPiNYI5DZvWuvHqebnKAR2_mrrkjlk" target=\"_blank\">A-1</a> (due 21 Aug)<br>
</td></tr>
<tr><td>Aug 18, Tue</td><td>L6</td><td>
Topics
<ul>
<li>Shear lag effect.</li>
<li>Limit state of block shear failure.</li>
<li>Other modes of failure of tension members – bearing, tearing, etc.</li>
</ul>

</td></tr>
<tr><td>Aug 20, Thu</td><td>L7</td><td>
Topics
<ul>
<li>Deflections and slenderness requirements for tension members.</li>
<li>Lug angles, splices, gusset plates and alignment of line of action forces for trusses.</li>
<li>Design of tension members.</li>
<li>Types of bolts, bolt actions, preload, load transfer mechanisms in bolted connections.</li>
<li><a href="https://www.youtube.com/watch?v=XLzTB4KLCxU&t=747s" target=\"_blank\">video on bolted connections</a></li>
</ul>

</td></tr>
<tr><td>Aug 21, Fri</td><td>T2</td><td>

Tutorial:
<a href="https://drive.google.com/drive/folders/1ybyPiNYI5DZvWuvHqebnKAR2_mrrkjlk" target=\"_blank\">T-2</a> <br>
Assignment:
<a href="https://drive.google.com/drive/folders/1ybyPiNYI5DZvWuvHqebnKAR2_mrrkjlk" target=\"_blank\">A-2</a> (due 28 Aug)<br>
</td></tr>
<tr><td>Aug 25, Tue</td><td>L8</td><td>
Topics
<ul>
<li>Design of bolted connections tension for tension members.</li>
<li>Shear failure, tension failure and bearing failure limit states of bolts.</li>
<li>Lap and butt joints. Cover and packing plates.</li>
<li>Prying action.</li>
</ul>

Project Tasks
<ul>
<li>Project 1, Tasks 1 & 2</li>
</ul>

</td></tr>
<tr><td>Aug 27, Thu</td><td>L9</td><td>
Topics
<ul>
<li>Design of bolted connections for prying action.</li>
<li>Welded connections; types of welds, weld defects and inspection.</li>
<li><a href="https://www.youtube.com/watch?v=p_0duihxmW4</li>
" target=\"_blank\">video on welded connections</a>
</ul>

Project Tasks
<ul>
<li>Project 2, Task 1</li>
</ul>

</td></tr>
<tr><td>Aug 28, Fri</td><td>T3</td><td>

Tutorial:
<a href="https://drive.google.com/drive/folders/1ybyPiNYI5DZvWuvHqebnKAR2_mrrkjlk" target=\"_blank\">T-3</a> <br>
Assignment:
<a href="https://drive.google.com/drive/folders/1ybyPiNYI5DZvWuvHqebnKAR2_mrrkjlk" target=\"_blank\">A-3</a> (due 3 Sep)<br>
</td></tr>
<tr><td>Sep 01, Tue</td><td>L10</td><td>
Topics
<ul>
<li>Design of welded connections for tension members.</li>
</ul>

Project Tasks
<ul>
<li>Project 1, Task 3</li>
</ul>

</td></tr>
<tr><td>Sep 03, Thu</td><td>L11</td><td>
Topics
<ul>
<li>Design of welded connections for tension members.</li>
</ul>

</td></tr>
<tr><td>Sep 04, Fri</td><td></td><td>
Janmashtami
</td></tr>
<tr><td>Sep 08, Tue</td><td>L12</td><td>
Topics
<ul>
<li>Plastic and local buckling analysis</li>
</ul>

</td></tr>
<tr><td>Sep 10, Thu</td><td>L13</td><td>
Topics
<ul>
<li>Plastic and local buckling analysis</li>
</ul>

Project Tasks
<ul>
<li>Project 2, Task 2</li>
</ul>

</td></tr>
<tr><td>Sep 11, Fri</td><td>T4</td><td>

</td></tr>
<tr><td>Sep 15, Tue</td><td>L14</td><td>
Topics
<ul>
<li>Design of compression members</li>
</ul>

Project Tasks
<ul>
<li>Project 1, Task 4</li>
</ul>

</td></tr>
<tr><td>Sep 17, Thu</td><td>L15</td><td>
Topics
<ul>
<li>Design of compression members</li>
</ul>

Project Tasks
<ul>
<li>Project 2, Task 3</li>
</ul>

</td></tr>
<tr><td></td><td></td><td>
Sep 18 to 23: Exam 1 window
</td></tr>
<tr><td>Sep 24, Thu</td><td>L16</td><td>
Topics
<ul>
<li>Design of beams</li>
</ul>

Project Tasks
<ul>
<li>Project 1, Task 5</li>
</ul>

</td></tr>
<tr><td>Sep 25, Fri</td><td>T5</td><td>

</td></tr>
<tr><td>Sep 29, Tue</td><td>L17</td><td>
Topics
<ul>
<li>Design of compression members</li>
</ul>

Project Tasks
<ul>
<li>Project 1, Task 6</li>
</ul>

</td></tr>
<tr><td>Oct 01, Thu</td><td>L18</td><td>
Topics
<ul>
<li>Design of compression members</li>
</ul>

Project Tasks
<ul>
<li>Project 1, Task 7</li>
</ul>

</td></tr>
<tr><td>Oct 02, Fri</td><td></td><td>
Gandhi Jayanti
</td></tr>
<tr><td>Oct 06, Tue</td><td>L19</td><td>
Topics
<ul>
<li>Design of beams</li>
</ul>

</td></tr>
<tr><td>Oct 08, Thu</td><td>L20</td><td>
Topics
<ul>
<li>Design of beams</li>
</ul>

Project Tasks
<ul>
<li>Project 2, Task 4</li>
</ul>

</td></tr>
<tr><td>Oct 09, Fri</td><td>T6</td><td>

</td></tr>
<tr><td>Oct 13, Tue</td><td>L21</td><td>
Topics
<ul>
<li>Bolted connections</li>
</ul>

Project Tasks
<ul>
<li>Project 2, Task 5</li>
</ul>

</td></tr>
<tr><td>Oct 15, Thu</td><td>L22</td><td>
Topics
<ul>
<li>Bolted connections</li>
</ul>

</td></tr>
<tr><td>Oct 16, Fri</td><td>T7</td><td>

</td></tr>
<tr><td></td><td></td><td>
Oct 17 to 25: Mid Semeseter Recess
</td></tr>
<tr><td>Oct 27, Tue</td><td>L23</td><td>
Topics
<ul>
<li>Welded connections</li>
</ul>

Project Tasks
<ul>
<li>Project 1, Task 8 begins</li>
</ul>

</td></tr>
<tr><td>Oct 29, Thu</td><td>L24</td><td>
Topics
<ul>
<li>Welded connections</li>
</ul>

</td></tr>
<tr><td>Oct 30, Fri</td><td>T8</td><td>

</td></tr>
<tr><td>Nov 03, Tue</td><td>L25</td><td>
Topics
<ul>
<li>Welded connections</li>
</ul>

</td></tr>
<tr><td>Nov 05, Thu</td><td>L26</td><td>
Topics
<ul>
<li>Welded connections</li>
</ul>

Project Tasks
<ul>
<li>Project 2, Task 6</li>
</ul>

</td></tr>
<tr><td>Nov 06, Fri</td><td>T9</td><td>

</td></tr>
<tr><td>Nov 10, Tue</td><td>L27</td><td>
Topics
<ul>
<li>Connections</li>
</ul>

Project Tasks
<ul>
<li>Project 1, Task 9</li>
</ul>

</td></tr>
<tr><td>Nov 12, Thu</td><td>L28</td><td>
Topics
<ul>
<li>Connections</li>
</ul>

Project Tasks
<ul>
<li>Project 1, Task 10</li>
<li>Project 2, Task 7</li>
</ul>

</td></tr>
<tr><td>Nov 13, Fri</td><td>T10</td><td>

</td></tr>
<tr><td></td><td></td><td>
Nov 20 to 28: Exam 2 window
</td></tr>
</table>
#+END_EXPORT
#+HTML: <small>
(Last updated: {{{mtime}}})
#+HTML: </small>
