#+TITLE: Students
#+OPTIONS: toc:nil title:nil
#+PROPERTY: HEADER-ARGS+ :eval no-export

* Doctoral Students
#+BEGIN_SRC emacs-lisp :results drawer :exports results
  (setq cv-buffer (find-file-noselect (concat gs-gscloud-d "/notes/elisp/cv.org")))

  (with-current-buffer cv-buffer
    (goto-char (point-min))
      (search-forward-regexp "^\* PhD Students$")
      (org-narrow-to-subtree)
      (forward-line)
      (setq my-text (buffer-substring-no-properties (point) (point-max)))
      ;(buffer-substring-no-properties (point) (point-max))
      (widen)
  );cv-buffer

  (print my-text)
#+END_SRC

#+RESULTS:
:results:
** Completed
1. Patnayakuni Ravi Prakash. September 2018. /Fully coupled multi-physics nonlinear analysis of structural systems subjected to fire/.
1. Nasar Ahmad Khan. September 2021. /Uncertainty quantification and design optimization of steel plate shear walls/.
1. Dharmit Nakrani. June 2024. /Material characterization and full-scale performance assessment of facade systems subjected to fire/.
1. Vikash Kumar Singh. February 2024. /Enhancing properties of cement, mortar and concrete through polymeric and nano additives/.
1. Dravesh Yadav. April 2025. /Thermo-mechanical analysis and design of aluminium structural systems subjected to fire/.
** Ongoing
1. Sheikh Mayesser Mushtaq. ongoing. /Enhancing properties of cement, mortar and concrete through polymeric and nano additives/.
1. Yajat Sharma. ongoing. /Fire egress modeling/.
:end:


* Masters Students
#+BEGIN_SRC emacs-lisp :results drawer :exports results
  (setq cv-buffer (find-file-noselect (concat gs-gscloud-d "/notes/elisp/cv.org")))

  (with-current-buffer cv-buffer
    (goto-char (point-min))
      (search-forward-regexp "^\* MTech Students$")
      (org-narrow-to-subtree)
      (forward-line)
      (setq my-text (buffer-substring-no-properties (point) (point-max)))
      ;(buffer-substring-no-properties (point) (point-max))
      (widen)
  );cv-buffer

  (print my-text)
#+END_SRC

#+RESULTS:
:results:
** Completed
1. Rujuta Bhat. July 2015. /Investigation of moisture transport properties of FAl-G bricks and cement mortar/.
1. Amar Mandhyan. July 2015. /Development of novel web application for analysis, design and optimization of trusses/.
1. Puneet Kumar. July 2015. /Characterization of in-plane and out-of-plane behavior of infill panels subjected to thermal exposure/.
1. Nikhil Singh. July 2016. /Topology optimization of beam-column subjected to axial and transverse loads considering effects of buckling/.
1. Atik Ghumde. July 2016. /Mesoscale modeling of concrete at elevated temperature/.
1. Pavan Kushwah. July 2016. /Physio-chemical characterization of cement mortar at high temperature/.
1. Satya Shrivastav. July 2016. /Toplogy optimization of steel girders subjected to thermal and mechanical loads/.
1. Harshal Lambhate. July 2017. /Comparative study of fire ratings of reinforced concrete beams and columns calculated through different analytical, empirical and codal methods/.
1. Sarana Hasanth Kota. August 2018. /A computationally efficient 1-D line element for modeling 3-D heat transfer in structural systems/.
1. Harsh Shah. August 2018. /Study of cement mortar reinforced with water-soluble polymer as admixture for high-temperature applications/.
1. Akshay Nandurkar. August 2018. /Design of facility for full-scale testing of structural elements under different fire scenarios/.
1. Neha Khairkar. October 2018. /Analysis and design of reaction wall system/.
1. Nikhil O. August 2019. /Influence of polyvinyl methyl ether on hydration of cement and high-temperature behaviour of cement mortar/.
1. Ravi Shankar. July 2019. /A new concept of augmenting steel plate shear wall with auxetic structure to enhance its energy dissipation/.
1. Prajjwal Patidar. December 2019. /Fire resistance of concrete filled steel tube columns protected by intumescent coating/.
1. Prerna Sarkar. January 2020. /Developing a device to reduce carbon dioxide emission from vehicle exhaust gas/.
1. Manu Mathur. July 2020. /Multi-physics modelling of effect of blast on a steel column protected with polyurethane foam/.
1. Rahul Khatri. July 2020. /Modelling and analysis of square tubular steel beams subjected to transverse blast loads using material point method/.
1. Ajay Chandran PV. October 2020. /Adsorption of the methylene blue from aqueous solution using geopolymer mortar grains in a fixed-bed column/.
1. Renjini R. July 2021. /Quantitative analysis and understanding of building fires in India/.
1. Drashti Shah. August 2021. /Characterization of fire behaviour inside non-AC rail coach/.
1. Pavithra CT. June 2021. /Characterization of fire behaviour in public transport buses/.
1. Vimal Panara. July 2022. /Analysis of RC Shear Wall subjected to thermal exposure/.
1. Prashant Singh. July 2022. /Analytical formulation of slab behavior at fire considering the effect of tensile membrane action/.
1. Sumit Kumar. August 2021. /Detailed combustion modeling of ACP components/.
1. Saurabh Kumar Sharma. October 2024. /Mitigation of Alcali-Silica Reaction in GGBS based geopolymer using LiOH/.
1. Aditi Parashar. July 2024. /Characterization and Evaluation of Copper Slag as an Alkali-Activated Cementitious Material/.
1. Gaurav Singh. August 2024. /Computational Modeling of Fire, Smoke and Egress in Metro Stations/.
1. Ashmita Dey. June 2025. /Influence of borax on the setting time and characterization of NaOH activated GGBS-based geopolymers/.
1. Kritika Rai. June 2025. /Thermal stability of alkali-activated GGBS using NaOH and LiOH as alkaline activators/.
1. Krishna Chaitanya Golamari. June 2025. /Reaction Mechanism and Micro-Structural Analysis of Ground Granulated Blast Furnace Slag Activated with Lithium Hydroxide/.
1. Venkata Valligatla. June 2025. /Microstructural Evolution and Hydration Mechanisms of GGBS activated with 5M Sodium Hydroxide/.
1. Choden Tamang. June 2025. /Effect of Titanium Diboride nanosheets on cement hydration and strength of cement mortar/.
** Ongoing
1. Darshan Dolas. ongoing. /Thesis work TBD/.
1. Ayush Kashyap. ongoing. /Thesis work TBD/.
1. Jaswant Rao. ongoing. /Thesis work TBD/.
1. Vikas Yadav. ongoing. /Thesis work TBD/.
1. Jeelkumar Tabiyar. ongoing. /Thesis work TBD/.
:end:

